import '@assets/styles/app.scss'
import React from "react";
import Providers from "@providers/with-providers";
import Header from "@components/Header";
import Footer from "@components/Footer/Footer";
import ToTopArrow from "@components/ToTopArrow/ToTopArrow";

export const metadata = {
    title: 'Лайм - доставка суши и пиццы',
    description: 'Generated by create next app',
    icons: {
        icon: '/images/favicon.ico',
        shortcut: '/images/favicon.ico',
        apple: '/images/favicon.ico',
    },
    verification: {
        google: 'google',
        yandex: 'yandex'
    },
}

const RootLayout = ({children}: { children: React.ReactNode }) => {
    return (
        <html lang="ru">
        <body className={`App`}>
        <Providers>
            <Header/>
            <main className="content">
                <div className="container">
                    {children}
                </div>
            </main>
            <Footer/>
            <ToTopArrow/>
        </Providers>
        </body>
        </html>
    )
}

export default RootLayout;